### PR TITLE
opencl 1.2, and 2.0 updates

### PR DESCRIPTION
**Pull request by nathanpackard**
added 2015 solution
added bindings classes, linked the classes to the demo project
additional support for opencl 1.2 functions
added support for opencl 2.0

### CODE REVIEW

**Comment by jcmontoute** [comment]
This looks fantastic - many thanks for the 2.0 support, especially. Is everything with in the OpenCL 2.0 spec included here?

A few suggestions:
* Let's rename CL*.cs to ICL*.cs
* We should rename dllCL*.cs to CL*.cs and move those into the bindings folder as well
* Would it be possible to wrap the DLL-linked classes in a define (something like INCLUDE_CL_IMPLEMENTATIONS)? With our Unity implementation, we have to include those files separately as source in order to properly exclude them from some of Unity's platforms that don't support OpenCL (iOS for example). I would set the VS2015 solution to enable that define by default, though (for general purpose use, or where platform-specific compilation in Unity isn't needed).

Thanks again for the contribution!

**Comment by nathanpackard** [comment]
Thanks! I believe everything from opencl 2.0 spec is included. I went through the cl.h file provided by khronos and added all the enums and new functions. We'll probably want to eventually setup new test cases to verify the new functions work (make sure I didn't make any mistakes in my p/invoke methods). I still want to go over my implementation once more to check for errors, for example, I want to make sure I used the correct data type (int vs long vs IntPtr) for my enum definitions.

* I fully agree we should rename CL to ICS and dllCL to CL.
* If possible, I think it would be nice to find a way to do some sort of DEFINE to specify the bindings classes you want as you suggested. I like the idea of keeping all the files as part of the library. I am also interested in mobile development and would like to make it easy to switch between implementations without having to search for the proper files to use.

I can rename things in my fork as you suggested, also I will think about how to do a conditional include in a clean way. 

Thanks!

**Comment by nathanpackard** [comment]
I'll wait till my fork is more stable

**Comment by jcmontoute** [comment]
Hey @nathanpackard, were there any updates on this?

**Pull request closed without merging**
